blogsite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    #post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('<int:year>/',views.PostYearArchiveView.as_view(), name="post_year_archive"),
]

# < > are used to capture values from the url . path converters are used to define the url patterns 

blogsite/blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts' : PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

# NSFProduction
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

blogsite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

# Adding a model manager, there aare two ways:
#  1. Add extra manager methods ( Post.objects.my_manager() )
#  2. Modify initial manager querysets  ( Post.my_manager.all() )
# create the class using manager querysets

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    """model describing posts on the blog"""
    objects = models.Manager() # The default manager
    published = PublishedManager() # our custom manager
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish') # unique_for_date ensures only one post with a given slug date for multiple posts on the same day
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, null=True,on_delete=models.CASCADE, related_name='+')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()
    class meta:
        ordering = ('-publish',)

    def __str__(self):
        """string representation of model object"""
        return self.title

    def get_absolute_url(self):
        """returns the url to accesss a detail record for this post"""
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    
class Comment(models.Model):
    """
    model representing comments on blog
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    # attribute allows us to name the attribute that we use for the relation from the
    #  related object back to this one.
    # Django will use the name of the model in lowercase, followed by _set to name the
    # manager of the related object
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) # for manually deactivating inappropriate comments,

    class Meta:
        ordering =('created',)
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}.'

blogsite/blog/forms.py
from django import forms
from .models import Comment, Post


class EmailPostForm(forms.Form):
    """
    class to deal with emails
    """
    name =  forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        widget=forms.Textarea,
        required=False)

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('name','email','body')


class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'status', 'tags', 'body', 'publish')

class PostUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('title', 'tags', 'body', 'status')

blogsite/blog/views.py
from django.shortcuts import render, get_object_or_404,get_list_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib  import messages
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic.list import ListView
from django.views.generic.dates import YearArchiveView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from .forms import EmailPostForm, CommentForm, PostCreateForm,PostUpdateForm
from django.core.mail import send_mail
from django.db.models import Count
# Create your views here.

def post_list(request, tag_slug=None):
    """ Creates a view displaying a list of all posts. """

    object_list = Post.published.all().order_by("id")
    tag = None
   

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug) # get tag object given slug
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 2) # limits it to n posts per page
    page = request.GET.get('page') # current page number

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If the page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If the page is out of range deliver last page of the results
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html', {'page':page, 'posts': posts, 'tag': tag})



def post_detail(request, year, month, day, post):
    """ Creates a view to show details of a single post. """
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    # posts_list = get_list_or_404(Post)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if  comment_form.is_valid():
            # create comment object but dont save to db
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            
            messages.success(request, "Comment added.")
        else:
            messages.error(request,"Error posting comment.")

    else:
        comment_form = CommentForm()
    
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
        
    return render(request, 'blog/post/detail.html', {'post': post,
                    'comments': comments,
                    'new_comments': new_comment,
                    'comment_form': comment_form,
                    'similar_posts': similar_posts
                    })


def post_share(request, post_id):
    """
    class describing email share
    """
    # retrieve the post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method =='POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
            # send email
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})
 
#  def post_edit(request, post_id)
# def post_edit(request, post):
#     """
#     create or edit posts
#     """
#     post = get_object_or_404(Post,pk=pk)
#     if request.method == 'POST':
#         post_form = PostForm(
#             instance=request.POST)
#         if post_form.is_valid():
#             post_form.save()
#     else:
#         post_form = PostForm()
#     return render(request,'blog/post/edit.html', {'post_form': post_form})

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post/post_create.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('post_list')

    def form_valid(self, form):
        """if form is valid save the model as"""
        post = form.save(commit=False)
        post.author = self.request.user.get_username()

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name = 'blog/post/post_update.html'
    context_object_name = 'post'
    pk_url_kwarg = 'pk'
    

    def form_valid(self, form):
        """
        extra fields are generated
        """
        post = form.save(commit=False)
        post.updated_by = self.request.user.get_username() # set user who updated form
        post.save()
        return super().form_valid(form)

class PostYearArchiveView(YearArchiveView):
    queryset = Post.objects.all()
    date_field = "publish"
    make_object_list = True
    allow_future = True
    template_name = "blog/base.html"

blogsite/blog/templates/blog/post/all_tags.html
{% load blog_tags %}
<!-- tags section  -->
<div class="row bottom tags-wrap">
    <div class="col-full tags">
        <h3>Tags</h3>
        
        <div class="tagcloud">
            {% for tag in all_tags %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug % }">{{ tag.name }}</a>
            {% endfor %}
        </div> <!-- end tagcloud -->
    </div> <!-- end tags -->
</div> <!-- end tags-wrap -->

blogsite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block header %}
<section class="s-pageheader s-pageheader--home">
    {% include "header.html" %}
</section>
{% endblock header %}

{% block content %}
  
<section class="s-content s-content--narrow s-content--no-padding-bottom">

    <article class="row format-standard">

        <div class="s-content__header col-full">
            <h1 class="s-content__header-title">
                {{ post.title }}
            </h1>
            <ul class="s-content__header-meta">
                <li class="date">{{ post.publish }}</li>
                <li class="cat">
                    In
                    {% for tag in post.tags.all  %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                    
                    {% endfor %}
                </li>
            </ul>
        </div> <!-- end s-content__header -->

        <div class="s-content__media col-full">
            <div class="s-content__post-thumb">
                <img src="images/thumbs/single/standard/standard-1000.jpg" 
                     srcset="images/thumbs/single/standard/standard-2000.jpg 2000w, 
                             images/thumbs/single/standard/standard-1000.jpg 1000w, 
                             images/thumbs/single/standard/standard-500.jpg 500w" 
                     sizes="(max-width: 2000px) 100vw, 2000px" alt="" >
            </div>
        </div> <!-- end s-content__media -->

        <div class="col-full s-content__main"></div>

            <p>
                {{ post.body }}
            </p>
            
            <p class="s-content__tags">
                <span>Post Tags</span>
                  
                <span class="s-content__tag-list">
                    {% for tag in post.tags.all  %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                    
                    {% endfor %}
                

            </p> <!-- end s-content__tags -->
            {% if user.is_authenticated %}
                  
                    </span>
                    <div class="col-four">
                    <span>
                        <a class="btn btn--primary" href="{% url 'blog:post_update' post.pk %}">Update Post</a>
                    </span>
                    </div>
                {% endif %}

            <!-- Author section  -->
            <div class="s-content__author">
                <img src="/static/images/avatars/user-03.jpg" alt="">

                <div class="s-content__author-about">
                    <h4 class="s-content__author-name">
                        <a href="#0">{{ post.author }}</a>
                    </h4>
                
                    <p>Alias aperiam at debitis deserunt dignissimos dolorem doloribus, fuga fugiat impedit laudantium magni maxime nihil nisi quidem quisquam sed ullam voluptas voluptatum. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                    </p>

                    <ul class="s-content__author-social">
                    <li><a href="#0">Facebook</a></li>
                    <li><a href="#0">Twitter</a></li>
                    <li><a href="#0">GooglePlus</a></li>
                    <li><a href="#0">Instagram</a></li>
                    </ul>
                </div>
            </div>


            <!-- Navigation section -->
             
                <div class="s-content__pagenav">
                    <div class="s-content__nav">
                        <div class="s-content__prev">
                            <a href="#0" rel="prev">
                                <span>Previous Post</span>
                                Tips on Minimalist Design 
                            </a>
                        </div>
                        <div class="s-content__next">
                            <a href="#0" rel="next">
                                <span>Next Post</span>
                                Less Is More 
                            </a>
                        </div>
                    </div>
                </div> <!-- end s-content__pagenav -->
        </div> <!-- end s-content__main -->
        
    </article>

    <!-- comments -->

    <div class="comments-wrap">

        <div id="comments" class="row">
            <div class="col-full">
                {% with comments.count as total_comments %}
                  
                <h3 class="h2">{{ total_comments}} comment{{ total_comments|pluralize }}</h3>

                {% endwith %}


                <!-- commentlist -->
                <ol class="commentlist">
                    {% for comment in comments  %}
                    
                        <li class="depth-1 comment">

                            <div class="comment__avatar">
                                <img width="50" height="50" class="avatar" src="images/avatars/user-01.jpg" alt="">
                            </div>

                            <div class="comment__content">

                                <div class="comment__info">
                                    <cite>{{ comment.name }} </cite>

                                    <div class="comment__meta">
                                        <time class="comment__time">{{ comment.created }}</time>
                                        <a class="reply" href="#0">Reply</a>
                                    </div>
                                </div>

                                <div class="comment__text">
                                <p>{{ comment.body|linebreaks }}</p>
                                </div>
                            </div>
                        </li> <!-- end comment level 1 -->
                    {% empty %}
                    <p>No comments yet.</p>
                    {% endfor %}
                    {% if new_comment %}
                        <h2>Your comment has been added.</h2>
                        <br>
                        <br>
                        
                    {% else %}

                        <h2>New comment</h2>
                        
                        <form action="." method="POST">
                            {% csrf_token %}
                            {{ comment_form.as_p }}
                            <p><input type="submit" value="Add comment"></p>
                        </form>
                    {% endif %}

                </ol>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block section %}
<h3>Similar Posts</h3>
<div class="block-1-2 block-m-full popular__posts">
    {% for post in similar_posts %}
        <article class="col-block popular__post">
            <a href="#0" class="popular__thumb">
                <img src="images/thumbs/small/wheel-150.jpg" alt="">
            </a>
            <h5><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
            <section class="popular__meta">
                    <span class="popular__author"><span>By</span> <a href="#0">{{ post.author }}</a></span>
                <span class="popular__date"><span>on</span> <time datetime="2017-12-19">{{ post.publish }}</time></span>
            </section>
        </article>
    {% empty %}
        <p>There are no similar posts yet.</p>
    {% endfor %}
</div>
{% endblock section %}

blogsite/blog/templates/blog/post/latest_posts.html
{% load blog_tags %}

<div class="pageheader-content row">
    <div class="col-full">

        <div class="featured">
             
            <div class="featured__column featured__column--big">
                <div class="entry" style="background-image:url('/static/images/thumbs/featured/featured-guitarman.jpg');">
                    
                    <div class="entry__content">
                        
                        <span class="entry__category"><a href="#">{{ latest_posts.0.tags.names.1 }}</a></span>

                        <h1><a href="{{ latest_posts.0.get_absolute_url }}" title="">{{ latest_posts.0.title }}</a></h1>

                        <div class="entry__info">
                            <a href="#0" class="entry__profile-pic">
                                <img class="avatar" src="{{ profile }}" alt="Profile picture">
                            </a>

                            <ul class="entry__meta">
                                <li><a href="#0">{{ latest_posts.0.author }}</a></li>
                                <li> {{ latest_posts.0.publish }}</li>
                            </ul>
                        </div>
                    </div> <!-- end entry__content -->
                    
                </div> <!-- end entry -->
            </div> <!-- end featured__big -->
            <div class="featured__column featured__column--small">

                <div class="entry" style="background-image:url('/static/images/thumbs/featured/featured-watch.jpg');">
                    
                    <div class="entry__content">
                        <span class="entry__category"><a href="#0">{{ latest_posts.1.tags.names.1 }}</a></span>
            
                        <h1><a href="{{ latest_posts.1.get_absolute_url }}" title="">{{ latest_posts.1.title }}</a></h1>
            
                        <div class="entry__info">
                            <a href="#0" class="entry__profile-pic">
                                <img class="avatar" src="/static/images/avatars/user-03.jpg" alt="">
                            </a>
            
                            <ul class="entry__meta">
                                <li><a href="#0">{{ latest_posts.1.author }}</a></li>
                                <li>{{ latest_posts.1.publish }}</li>
                            </ul>
                        </div>
                    </div> <!-- end entry__content -->
                  
                </div> <!-- end entry -->
            
                <div class="entry" style="background-image:url('/static/images/thumbs/featured/featured-beetle.jpg');">
            
                    <div class="entry__content">
                        <span class="entry__category"><a href="#0">{{ latest_posts.2.tags.names.1 }}</a></span>
            
                        <h1><a href="{{ latest_posts.2.get_absolute_url }}" title="">{{ latest_posts.2.title }}</a></h1>
            
                        <div class="entry__info">
                            <a href="#0" class="entry__profile-pic">
                                <img class="avatar" src="/static/images/avatars/user-03.jpg" alt="">
                            </a>
            
                            <ul class="entry__meta">
                                <li><a href="#0">{{ latest_posts.2.author }}</a></li>
                                <li>{{ latest_posts.2.publish }}</li>
                            </ul>
                        </div>
                    </div> <!-- end entry__content -->
            
                </div> <!-- end entry -->
            
            </div> <!-- end featured__small -->
            

        </div> <!-- end featured -->

    </div> <!-- end col-full -->
</div> <!-- end pageheader-content row -->

blogsite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load static %}



<title> {% block title %}
  {{ post.title}}
{% endblock title %}</title>

{% block content %}
<section class="s-content">
        
    <div class="row masonry-wrap">
        <div class="masonry">

            <div class="grid-sizer"></div>
    
                {% for post in posts %}
                
                <article class="masonry__brick entry format-standard" data-aos="fade-up">

                    <div class="entry__thumb">
                        <a href="{{ post.get_absolute_url }}" class="entry__thumb-link">
                            <img src="{% static 'images/thumbs/masonry/cookies-400.jpg' %}" 
                                    alt=""> <!-- srcset="images/thumbs/masonry/cookies-400.jpg 1x images/thumbs/masonry/cookies-800.jpg 2x" -->
                        </a>
                    </div>

                    <div class="entry__text">
                        <div class="entry__header">
                            
                            <div class="entry__date">
                                <a href="{{ post.get_absolute_url }}">{{ post.publish }}</a>
                            </div>
                            <h1 class="entry__title"><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a></h1>
                            
                        </div>
                        <div class="entry__excerpt">
                            <p>
                                {{ post.body|truncatewords_html:10 }}
                            </p>
                        </div>
                        
                        <div class="entry__meta">
                            <span class="entry__meta-links">
                                {% for tag in post.tags.all  %}
                                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                                    {{ tag.name }}
                                    </a>
                                {% endfor %}
                            </span>
                        </div>   
                    </div>
                    

                </article> <!-- end article -->

            {% endfor %}
        </div>
    </div>

    {% include "pagination.html" with page=posts %}
</section> <!-- s-content -->
{% endblock content %}

blogsite/blog/templates/blog/post/post_create.html
{% extends "blog/post/detail.html" %}

{% block content %}
<section class="s-content s-content--narrow s-content--no-padding-bottom">

    <article class="row format-standard">
        <h2>New post</h2>
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <p><input type="submit" value="Publish Post"></p>
        </form>
    </article>
</section>
{% endblock content %}

blogsite/blog/templates/blog/post/post_update.html
{% extends "blog/post/detail.html" %}

{% block content %}
<section class="s-content s-content--narrow s-content--no-padding-bottom">

    <article class="row format-standard">
        <h2>Update post</h2>
        <p>Some changes no prob..</p>

        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}

            <p><input type="submit" value="Update Post"></p>
        </form>
    </article>
</section>
{% endblock content %}