blogsite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    #post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('<int:year>/',views.PostYearArchiveView.as_view(), name="post_year_archive"),
]

# < > are used to capture values from the url . path converters are used to define the url patterns 

blogsite/blogsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts' : PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

# NSFProduction
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

blogsite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

# Adding a model manager, there aare two ways:
#  1. Add extra manager methods ( Post.objects.my_manager() )
#  2. Modify initial manager querysets  ( Post.my_manager.all() )
# create the class using manager querysets

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')

class Post(models.Model):
    """model describing posts on the blog"""
    objects = models.Manager() # The default manager
    published = PublishedManager() # our custom manager
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish') # unique_for_date ensures only one post with a given slug date for multiple posts on the same day
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(User, null=True,on_delete=models.CASCADE, related_name='+')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()
    class meta:
        ordering = ('-publish',)

    def __str__(self):
        """string representation of model object"""
        return self.title

    def get_absolute_url(self):
        """returns the url to accesss a detail record for this post"""
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])
    
class Comment(models.Model):
    """
    model representing comments on blog
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    # attribute allows us to name the attribute that we use for the relation from the
    #  related object back to this one.
    # Django will use the name of the model in lowercase, followed by _set to name the
    # manager of the related object
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) # for manually deactivating inappropriate comments,

    class Meta:
        ordering =('created',)
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}.'

blogsite/blog/forms.py
from django import forms
from .models import Comment, Post


class EmailPostForm(forms.Form):
    """
    class to deal with emails
    """
    name =  forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        widget=forms.Textarea,
        required=False)

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('name','email','body')


class PostCreateForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'status', 'tags', 'body', 'publish')

class PostUpdateForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('title', 'tags', 'body', 'status')

blogsite/blog/views.py
from django.shortcuts import render, get_object_or_404,get_list_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib  import messages
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic.list import ListView
from django.views.generic.dates import YearArchiveView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from .forms import EmailPostForm, CommentForm, PostCreateForm,PostUpdateForm
from django.core.mail import send_mail
from django.db.models import Count
# Create your views here.

def post_list(request, tag_slug=None):
    """ Creates a view displaying a list of all posts. """

    object_list = Post.published.all().order_by("id")
    tag = None
   

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug) # get tag object given slug
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 2) # limits it to n posts per page
    page = request.GET.get('page') # current page number

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If the page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If the page is out of range deliver last page of the results
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html', {'page':page, 'posts': posts, 'tag': tag})



def post_detail(request, year, month, day, post):
    """ Creates a view to show details of a single post. """
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    # posts_list = get_list_or_404(Post)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if  comment_form.is_valid():
            # create comment object but dont save to db
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            
            messages.success(request, "Comment added.")
        else:
            messages.error(request,"Error posting comment.")

    else:
        comment_form = CommentForm()
    
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
        
    return render(request, 'blog/post/detail.html', {'post': post,
                    'comments': comments,
                    'new_comments': new_comment,
                    'comment_form': comment_form,
                    'similar_posts': similar_posts
                    })


def post_share(request, post_id):
    """
    class describing email share
    """
    # retrieve the post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method =='POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
            # send email
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})
 
#  def post_edit(request, post_id)
# def post_edit(request, post):
#     """
#     create or edit posts
#     """
#     post = get_object_or_404(Post,pk=pk)
#     if request.method == 'POST':
#         post_form = PostForm(
#             instance=request.POST)
#         if post_form.is_valid():
#             post_form.save()
#     else:
#         post_form = PostForm()
#     return render(request,'blog/post/edit.html', {'post_form': post_form})

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post/post_create.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('post_list')

    def form_valid(self, form):
        """if form is valid save the model as"""
        post = form.save(commit=False)
        post.author = self.request.user.get_username()

class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name = 'blog/post/post_update.html'
    context_object_name = 'post'
    pk_url_kwarg = 'pk'
    

    def form_valid(self, form):
        """
        extra fields are generated
        """
        post = form.save(commit=False)
        post.updated_by = self.request.user.get_username() # set user who updated form
        post.save()
        return super().form_valid(form)

class PostYearArchiveView(YearArchiveView):
    queryset = Post.objects.all()
    date_field = "publish"
    make_object_list = True
    allow_future = True
    template_name = "blog/base.html"

blogsite/blog/templates/footer.html
 <!-- s-footer
    ================================================== -->
    <footer class="s-footer">

        <div class="s-footer__main">
            <div class="row">
                
                <div class="col-two md-four mob-full s-footer__sitelinks">
                        
                    <h4>Quick Links</h4>

                    <ul class="s-footer__linklist">
                        <li><a href="{% url 'blog:post_list' %}">Home</a></li>
                        <!-- <li><a href="#0">Blog</a></li> -->
                        <!-- <li><a href="#0">Styles</a></li> -->
                        <li><a href="#0">About</a></li>
                        <li><a href="#0">Contact</a></li>
                        <li><a href="#0">Privacy Policy</a></li>
                    </ul>

                </div> <!-- end s-footer__sitelinks -->

                <div class="col-two md-four mob-full s-footer__archives">
                        
                    <h4>Archives</h4>

                    <ul class="s-footer__linklist">
                        {% for date in date_list %}
                            <li>{{ date|date:"F Y" }}</li>
                        {% endfor %}
                        <li>All Articles for {{ year|date:"Y" }}</li>
                        <li><a href="#0">January 2018</a></li>
                        <!-- <li><a href="#0">December 2017</a></li>
                        <li><a href="#0">November 2017</a></li>
                        <li><a href="#0">October 2017</a></li>
                        <li><a href="#0">September 2017</a></li>
                        <li><a href="#0">August 2017</a></li> -->
                    </ul>

                </div> <!-- end s-footer__archives -->

                <div class="col-two md-four mob-full s-footer__social">
                        
                    <h4>Social</h4>

                    <ul class="s-footer__linklist">
                        <li><a href="#0">Facebook</a></li>
                        <li><a href="#0">Instagram</a></li>
                        <li><a href="#0">Twitter</a></li>
                        <li><a href="#0">Pinterest</a></li>
                        <li><a href="#0">Google+</a></li>
                        <li><a href="#0">LinkedIn</a></li>
                    </ul>

                </div> <!-- end s-footer__social -->

                <div class="col-five md-full end s-footer__subscribe">
                        
                    <h4>Our Newsletter</h4>

                    <p>Sit vel delectus amet officiis repudiandae est voluptatem. Tempora maxime provident nisi et fuga et enim exercitationem ipsam. Culpa consequatur occaecati.</p>

                    <div class="subscribe-form">
                        <form id="mc-form" class="group" novalidate="true">

                            <input type="email" value="" name="EMAIL" class="email" id="mc-email" placeholder="Email Address" required="">
                
                            <input type="submit" name="subscribe" value="Send">
                
                            <label for="mc-email" class="subscribe-message"></label>
                
                        </form>
                    </div>

                </div> <!-- end s-footer__subscribe -->

            </div>
        </div> <!-- end s-footer__main -->

        <div class="s-footer__bottom">
            <div class="row">
                <div class="col-full">
                    <div class="s-footer__copyright">
                        <span>© Copyright Philosophy 2018</span> 
                        <span>Site Template by <a href="https://colorlib.com/">Colorlib</a></span>
                    </div>

                    <div class="go-top">
                        <a class="smoothscroll" title="Back to Top" href="#top"></a>
                    </div>
                </div>
            </div>
        </div> <!-- end s-footer__bottom -->

    </footer> <!-- end s-footer -->


    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader">
            <div class="line-scale">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>

blogsite/blog/templates/header.html
{% load static %}

<header class="header">
    <div class="header__content row">

        <div class="header__logo">
            <a class="logo" href="index.html">
                <img src="images/logo.svg" alt="Homepage">
            </a>
        </div> <!-- end header__logo -->

        <ul class="header__social">
            <li>
                <a href="#0"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            </li>
            <li>
                <a href="#0"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </li>
            <li>
                <a href="#0"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            </li>
            <li>
                <a href="#0"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
            </li>
        </ul> <!-- end header__social -->

        <a class="header__search-trigger" href="#0"></a>

        <div class="header__search">

            <form role="search" method="get" class="header__search-form" action="#">
                <label>
                    <span class="hide-content">Search for:</span>
                    <input type="search" class="search-field" placeholder="Type Keywords" value="" name="s" title="Search for:" autocomplete="off">
                </label>
                <input type="submit" class="search-submit" value="Search">
            </form>

            <a href="#0" title="Close Search" class="header__overlay-close">Close</a>

        </div>  <!-- end header__search -->


        <a class="header__toggle-menu" href="#0" title="Menu"><span>Menu</span></a>

        <nav class="header__nav-wrap">

            <h2 class="header__nav-heading h6">Site Navigation</h2>

            <ul class="header__nav">
                <li class="current"><a href="index.html" title="">Home</a></li>
                <li class="has-children">
                    <a href="#0" title="">Categories</a>
                    <ul class="sub-menu">
                    <li><a href="category.html">Lifestyle</a></li>
                    <li><a href="category.html">Health</a></li>
                    <li><a href="category.html">Family</a></li>
                    <li><a href="category.html">Management</a></li>
                    <li><a href="category.html">Travel</a></li>
                    <li><a href="category.html">Work</a></li>
                    </ul>
                </li>
            
                <li><a href="about.html" title="">About</a></li>
                <li><a href="contact.html" title="">Contact</a></li>
            </ul> <!-- end header__nav -->

            <a href="#0" title="Close Menu" class="header__overlay-close close-mobile-menu">Close</a>

        </nav> <!-- end header__nav-wrap -->

    </div> <!-- header-content -->
</header> <!-- header -->
        


    
    

blogsite/blog/templates/pagination.html
<div class="row">
    <div class="col-full">
        <nav class="pgn">
            <ul>
                {% if page.previous %}
                <li><a class="pgn__prev" href="?page={{ page.previous_page_number ">Prev</a></li>
                {% endif %}

                {% for num in page.paginator.page_range %}
                
                    {% if page.number == num %}
                        <li><span class="pgn__num current">{{ num }}</span></li>
                    {% elif num > page.number|add:'-2' and num < page.number|add:'2' %} <!--test -->
                        <li><a class="pgn__num" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
          
                {% endfor %}

                <li><span class="pgn__num dots">…</span></li>
               
                {% if page.has_next %}
                  <li><a class="pgn__next" href="?page={{ page.next_page_number }}">Next</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

blogsite/blog/templates/scripts.html
{% load static %}
<!-- Java Script
    ================================================== -->
    
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

blogsite/blog/templates/section.html
    <!-- s-extra
    ================================================== -->
    <h3>Popular Posts</h3>
    <div class="block-1-2 block-m-full popular__posts">
        <article class="col-block popular__post">
            <a href="#0" class="popular__thumb">
                <img src="images/thumbs/small/wheel-150.jpg" alt="">
            </a>
            <h5><a href="#0">Visiting Theme Parks Improves Your Health.</a></h5>
            <section class="popular__meta">
                    <span class="popular__author"><span>By</span> <a href="#0"> John Doe</a></span>
                <span class="popular__date"><span>on</span> <time datetime="2017-12-19">Dec 19, 2017</time></span>
            </section>
        </article>
        <article class="col-block popular__post">
            <a href="#0" class="popular__thumb">
                <img src="images/thumbs/small/shutterbug-150.jpg" alt="">
            </a>
            <h5><a href="#0">Key Benefits Of Family Photography.</a></h5>
            <section class="popular__meta">
                <span class="popular__author"><span>By</span> <a href="#0"> John Doe</a></span>
                <span class="popular__date"><span>on</span> <time datetime="2017-12-18">Dec 18, 2017</time></span>
            </section>
        </article>
        <article class="col-block popular__post">
            <a href="#0" class="popular__thumb">
                <img src="images/thumbs/small/cookies-150.jpg" alt="">
            </a>
            <h5><a href="#0">Absolutely No Sugar Oatmeal Cookies.</a></h5>
            <section class="popular__meta">
                    <span class="popular__author"><span>By</span> <a href="#0"> John Doe</a></span>
                <span class="popular__date"><span>on</span> <time datetime="2017-12-16">Dec 16, 2017</time></span>
            </section>
        </article>
        <article class="col-block popular__post">
            <a href="#0" class="popular__thumb">
                <img src="images/thumbs/small/beetle-150.jpg" alt="">
            </a>
            <h5><a href="#0">Throwback To The Good Old Days.</a></h5>
            <section class="popular__meta">
                <span class="popular__author"><span>By</span> <a href="#0"> John Doe</a></span>
                <span class="popular__date"><span>on</span> <time datetime="2017-12-16">Dec 16, 2017</time></span>
            </section>
        </article>
        <article class="col-block popular__post">
            <a href="#0" class="popular__thumb">
                <img src="images/thumbs/small/tulips-150.jpg" alt="">
            </a>
            <h5><a href="#0">10 Interesting Facts About Caffeine.</a></h5>
            <section class="popular__meta">
                <span class="popular__author"><span>By</span> <a href="#0"> John Doe</a></span>
                <span class="popular__date"><span>on</span> <time datetime="2017-12-14">Dec 14, 2017</time></span>
            </section>
        </article>
        <article class="col-block popular__post">
            <a href="#0" class="popular__thumb">
                <img src="images/thumbs/small/salad-150.jpg" alt="">
            </a>
            <h5><a href="#0">Healthy Mediterranean Salad Recipes</a></h5>
            <section class="popular__meta">
                <span class="popular__author"><span>By</span> <a href="#0"> John Doe</a></span>
                <span class="popular__date"><span>on</span> <time datetime="2017-12-12">Dec 12, 2017</time></span>
            </section>
        </article>
    </div> <!-- end popular_posts -->
                
    

        

        

    